DROP DATABASE IF EXISTS TRUONGHOC1;

CREATE DATABASE TRUONGHOC1;

USE TRUONGHOC1;

DROP TABLE IF EXISTS TRUONG;

CREATE TABLE TRUONG (
    MATR varchar(10) NOT NULL,
    TENTR varchar(50) NOT NULL,
    DCHITR varchar(225) NOT NULL,
    PRIMARY KEY (MATR)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS HS;

CREATE TABLE HS(
    MAHS varchar(10) NOT NULL,
    HO varchar(30) NOT NULL,
    TEN varchar(30) NOT NULL,
    CCCD varchar(15) UNIQUE,
    NTNS date NOT NULL,
    DIACHI_HS varchar(225) NOT NULL,
    PRIMARY KEY (MAHS)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS HOC;

CREATE TABLE HOC(
    MATR varchar(10) NOT NULL,
    MAHS varchar(10) NOT NULL,
    NAMHOC varchar(10) NOT NULL,
    DIEMTB decimal(5,2) DEFAULT NULL,
    XEPLOAI varchar(15) DEFAULT NULL,
    KQUA varchar(20) DEFAULT NULL,
    PRIMARY KEY (MATR,MAHS,NAMHOC),
    CONSTRAINT FOREIGN KEY (MATR) REFERENCES TRUONG(MATR),
    CONSTRAINT FOREIGN KEY (MAHS) REFERENCES HS(MAHS)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TRUONG ADD INDEX(MATR) USING BTREE;
ALTER TABLE HS ADD INDEX(MAHS) USING BTREE;
ALTER TABLE HOC ADD INDEX(MATR,MAHS,NAMHOC) USING BTREE;